version: '3.9'

services:
  db:
    image: postgres:14
    container_name: faq_postgres
    restart: always
    environment:
      POSTGRES_DB: faq_db
      POSTGRES_USER: faq_user
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: faq_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: faq_django
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=faq_db
      - DB_USER=faq_user
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - DEBUG=False
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "frequently_asked_questions.wsgi:application"]

volumes:
  postgres_data:
